### ISSUE TITLE
Bundling with Webpack doesn't work well

### ISSUE THREAD

**Issue by designeng** [cujojs/wire#178]
When I try to build with Webpack I have a lot of warnings and errors, the first message

```
WARNING in ./node_modules/wire/wire.js
Critical dependencies:
29:27-34 require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/wire/wire.js 29:27-34
```

**Comment by designeng** [comment]
There is the problem with webpack relationship with `require` function.
Webpack tries to evaluate the request expression in the line https://github.com/cujojs/wire/blob/master/wire.js#L25. As the result the context module created by webpack has all inner files mapped.
I will try to workaround it with ContextReplacementPlugin.

**Comment by briancavalier** [comment]
Hey @designeng, thanks for investigating this and posting a followup.  It'll be helpful for others who may run into the same warning.

**Comment by saunders99999** [comment]
Hi @designeng / @briancavalier,

Are there any usage samples of wire and webpack?  I'm not sure how to have webpack bundle/load the wire library and then read wire specs.  I appreciate the post and see deisgneng is working on a webpack loader for wire, but I can't tell how mature that effort is.

Thanks...
